# SPDX-License-Identifier: GPL-2.0
# Athira Rajeev <atrajeev@linux.vnet.ibm.com>, 2023

PROGS = $(subst ./,,$(shell find tests/shell -perm -o=x -type f -name '*.sh'))
DEPS = $(addprefix output/,$(addsuffix .dep,$(basename $(PROGS))))
DIRS = $(shell echo $(dir $(DEPS)) | xargs -n1 | sort -u | xargs)

.PHONY: all
all: SHELLCHECK_RUN
	@:

SHELLCHECK_RUN: $(DEPS) $(DIRS)

output/%.dep: %.sh | $(DIRS)
	$(call rule_mkdir)
	$(eval input_file := $(subst output/,./,$(patsubst %.dep, %.sh, $@)))
	$(Q)$(call frecho-cmd,test)@shellcheck -S warning ${input_file} 1> $@.log && ([[ ! -s $@.log ]])
	$(Q)$(call frecho-cmd,test)@touch $@
	$(Q)$(call frecho-cmd,test)@rm -rf $@.log
$(DIRS):
	@mkdir -p $@

clean:
	@rm -rf output
